
data_files:
    - storage: public
      url: path_a_data

bigquery:
  project_id: 'corded-cortex-312822'
  credentials: '/home/federico/federico/SSYT/ssyt/ssyt/config/corded-cortex-312822-b9a0b32e4518.json'
