apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssyt
  template:
    metadata:
      labels:
        app: ssyt
    spec:
      containers:
        - name: ssyt # try ssyt-cluster (cluster name)
          image: gcr.io/ssyt-342721/ssyt:v1
          resources:
            requests:
              memory: "2000Mi"
